### ISSUE TITLE
Proposal peer review

### ISSUE THREAD

**Issue by Bolajiadewal3** [INFO-526-S24/project-final-GraphGeeks#3]
The following is the peer review of the project proposal by [name of team completing peer review]. The team members that participated in this review are 

- [Mobolaji Adewale] - @[bolajiadewal3]
- [Narasimha Vardhan Rachaputi] - @[nvrachaputi]
- [Usama Ahmed] - @[usamaahmedsh]
- [Pradnya Raut] - @[PradnyaR24]
- [Praveen Kumar Pappala] - @[Praveen-Kumar-Pappala]
- [Tushar Kant Singh] - @[ustusharkant]

- Describe the goal of the project.
The goal appears to be to collect and clean COVID-19 data and visualise said data in a meaningful way to allow people to take action during the global pandemic.

- Describe the data used or collected.
Three Kaggle datasets are to be used for this project: one containing global day-by-day pandemic data; another containing specific country data and; a third consisting of county-specific data within the United States only.

- Describe how the research question will be answered, e.g. what approaches / methods will be used.
The first question seems to be an exploration of the impact of the relationships between differing COVID-19 metrics. To answer this, they will use time-series plots to show the trend of the active, recovered and mortal cases; then correlation plots to identify the rate of change of these metrics to highlight their evolution over the pandemic's lifetime - The data will initially be per day.

The second question explores how the vaccination rate and new case rates changed over time in the USA. This will be answered via chloropleth and bubble plots, plus a time-lapse to show change over time of the two variables.

- Is there anything that is unclear from the proposal?
For the first question, it is not clear as to which exact timespans will be averaged (i.e. every two days, every fortnight, or the totality of the pandemic's lifetime). Additionally, correlation plots will not elucidate causality, it is slightly unclear whether it is implied or not in the research question.

The second question doesn't highlight the benefit of using two plots that seem to showcase the same data. It is slightly unclear whether the aim of the  density plots is to showcase a trend / changes over time or merely which counties were impacted most heavily. The plots may overcomplicate interpretations of the data.

- Provide constructive feedback on how the team might be able to improve their project.
A testing of the hypothesis like a t-test for linear relationship could be coupled with the correlation plot to make it clear whether the data are correlated and causated, or merely correlated. For the second question it may be beneficial to specify whether the plots will be side-by-side, overlayed or otherwise situated to showcase the trend.

- What aspect of this project are you most interested in and would like to see highlighted in the presentation.
The time-lapse visualisation of the changes in vaccinations and COVID-19 cases seems interesting. The Shiny app seems like it would end up being interesting to view.

- Provide constructive feedback on any issues with file and/or code organization.
The file displayed correctly on the website and has a simple presentation.

- (Optional) Any further comments or feedback?

**Comment by vemuladevendran** [comment]
## Response to Feedback

We are grateful for the further detailed feedback and have made the following clarifications and enhancements to our proposal:

### For Question 1:
- We've specified that our analysis will utilize a 7-day rolling average to provide clarity on the timespans used for averaging, enabling us to smooth daily data while retaining visibility of broader trends.
- We acknowledge the limitations of correlation plots in determining causality and have clarified in our proposal that these plots are intended to identify potential relationships, not to imply direct causality.

### For Question 2:
- We've elucidated the rationale behind our choice of visualizations. The choropleth and bubble maps are designed to complement each other, offering both a geographical density perspective and a magnitude representation to facilitate a multifaceted analysis of the data.
- We've ensured that the purpose and intended interpretation of each plot is communicated to prevent any overcomplication and to allow straightforward insights into the pandemic's impact across different counties.

These refinements aim to address the concerns raised and to enhance the clarity and effectiveness of our analysis. We appreciate the opportunity to refine our approach based on this valuable feedback.
