### ISSUE TITLE
Code peer review

### ISSUE THREAD

**Issue by Melissajiayue** [INFO-526-S24/project-final-GraphGeeks#6]
The following is the peer review of the project code by [name of team completing peer review]. The team members that participated in this review are 

- Varun Sahdev - @solitudevedhas
- Sanja Dmitrovic - @sdmitrovic
- Naitik Shah - @naitik2608
- Mohammad Farmani - @mfarmani95
- Jiayue - @Melissajiayue
- Vidhyananth - @Vidhyananth Sivashanmugam
---

#### 1. Purpose of Code
- [  ] Clearly defined and understood
- [ ✅] Ambiguous or unclear

---

#### 2. Code Quality

- [✅ ] Code is clean, readable, and well-organized
- [     ] Adequate comments explaining complex or tricky code sections
- [✅ ] Variables, methods, and classes have meaningful names
- [ ✅] Consistent code style (indentation, naming conventions, etc.)

---

#### 3. Documentation

- [ ] Code documentation (e.g., comments) is sufficient
- [ ] Readme or other documentation updated if necessary

---

#### 4. Best Practices

- [✅ ] No hardcoded values; constants used appropriately
- [✅ ] Security and privacy concerns addressed (e.g., no sensitive data exposed)
- [✅ ] Code avoids repetition and promotes reusability

---

#### 5. Additional Comments

- Please provide feedback, areas of improvement, or other observations.

Add more comments which helps readers to understand what the chunk of code is doing. And it helpful for debugging. 
Please update the readme file later. 
Put the link to Github page to the icon on your website. 
---

#### 6. Recommendation

- [ ] Approved - ready to be merged
- [ ✅] Approved with minor issues - can be addressed later
- [ ] Requires changes - provide feedback and request another review

---

**Comment by Gowtham-18** [comment]
Certainly! I agree that adding more detailed comments will help readers to understand the code even more. Will update the readme file too.
Thanks for the feedback!
