### ISSUE TITLE
Presentation peer review by Graphical Geniuses

### ISSUE THREAD

**Issue by ustusharkant** [INFO-526-S24/project-final-GraphGeeks#9]
The following is the peer review of the Presentation proposal by [name of team completing peer review]. The team members that participated in this review are 

-[Mobolaji Adewale] - @[bolajiadewal3]
-[Narasimha Vardhan Rachaputi] - @[nvrachaputi]
-[Usama Ahmed] - @[usamaahmedsh]
-[Pradnya Raut] - @[PradnyaR24]
-[Praveen Kumar Pappala] - @[Praveen-Kumar-Pappala]
-[Tushar Kant Singh] - @[ustusharkant]
- ...

- Content: Is the research question well designed and is the data being used relevant to the research question?

Yes, the data was relevant to the presentation given.

- Content: Did the team use appropriate visualizations and did they interpret them accurately?

Yes, the time series graph was clearly designed, informative but font & legends were too small to read. 

- Creativity and Critical Thought: Is the project carefully thought out? Are the limitations carefully considered? Does it appear that time and effort went into the planning and implementation of the project?

Yes the project was well thought through. Yes limitations carefully considered. Indeed they put time and effort to plan and implement the project.

- Slides: Are the slides well organized, readable, not full of text, featuring figures with legible labels, legends, etc.?
Slides are well organized but background color of image chosen for Q1  could have been bit darker as it was matching with the plot area and making the plot illegible. 

Font size could have been little bigger in order to make the labels & legends more readable.
Team could have used the more space of screen as there were lot of empty space below the plots.

- Professionalism: How well did the team present? Does the presentation appear to be well practiced? Are they reading off of a script? Did everyone get a chance to say something meaningful about the project?
1. Introduction, approach, topic idea and conclusion was clear
2. ⁠Some times the voice of team was very low and inaudible 
3. It seemed like some people had done their research and knew more than other team members & some were just reading the slides.
4. Yes every one got chance to present & say something meaningful.

**Comment by vemuladevendran** [comment]
Thanks for the review
